// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUSEREMAIL holds the string denoting the user_email field in the database.
	FieldUSEREMAIL = "user_email"
	// FieldUSERPASSWORD holds the string denoting the user_password field in the database.
	FieldUSERPASSWORD = "user_password"
	// FieldUSERNAME holds the string denoting the user_name field in the database.
	FieldUSERNAME = "user_name"

	// EdgeOrderUserr holds the string denoting the order_userr edge name in mutations.
	EdgeOrderUserr = "order_userr"

	// Table holds the table name of the user in the database.
	Table = "users"
	// OrderUserrTable is the table the holds the order_userr relation/edge.
	OrderUserrTable = "orders"
	// OrderUserrInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrderUserrInverseTable = "orders"
	// OrderUserrColumn is the table column denoting the order_userr relation/edge.
	OrderUserrColumn = "user_order_userr"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUSEREMAIL,
	FieldUSERPASSWORD,
	FieldUSERNAME,
}
