// Code generated by entc, DO NOT EDIT.

package equipment

const (
	// Label holds the string label denoting the equipment type in the database.
	Label = "equipment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEQUIPMENTNAME holds the string denoting the equipment_name field in the database.
	FieldEQUIPMENTNAME = "equipment_name"
	// FieldEQUIPMENTPRICE holds the string denoting the equipment_price field in the database.
	FieldEQUIPMENTPRICE = "equipment_price"

	// EdgeOrderEquipmentt holds the string denoting the order_equipmentt edge name in mutations.
	EdgeOrderEquipmentt = "order_equipmentt"

	// Table holds the table name of the equipment in the database.
	Table = "equipment"
	// OrderEquipmenttTable is the table the holds the order_equipmentt relation/edge.
	OrderEquipmenttTable = "orders"
	// OrderEquipmenttInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrderEquipmenttInverseTable = "orders"
	// OrderEquipmenttColumn is the table column denoting the order_equipmentt relation/edge.
	OrderEquipmenttColumn = "equipment_order_equipmentt"
)

// Columns holds all SQL columns for equipment fields.
var Columns = []string{
	FieldID,
	FieldEQUIPMENTNAME,
	FieldEQUIPMENTPRICE,
}
