// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// Equipment is the predicate function for equipment builders.
type Equipment func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
