// Code generated by entc, DO NOT EDIT.

package order

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAMOUNT holds the string denoting the amount field in the database.
	FieldAMOUNT = "amount"
	// FieldPRICE holds the string denoting the price field in the database.
	FieldPRICE = "price"
	// FieldADDEDTIME holds the string denoting the added_time field in the database.
	FieldADDEDTIME = "added_time"

	// EdgeEquipment holds the string denoting the equipment edge name in mutations.
	EdgeEquipment = "equipment"
	// EdgeCompany holds the string denoting the company edge name in mutations.
	EdgeCompany = "company"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the order in the database.
	Table = "orders"
	// EquipmentTable is the table the holds the equipment relation/edge.
	EquipmentTable = "orders"
	// EquipmentInverseTable is the table name for the Equipment entity.
	// It exists in this package in order to avoid circular dependency with the "equipment" package.
	EquipmentInverseTable = "equipment"
	// EquipmentColumn is the table column denoting the equipment relation/edge.
	EquipmentColumn = "equipment_order_equipmentt"
	// CompanyTable is the table the holds the company relation/edge.
	CompanyTable = "orders"
	// CompanyInverseTable is the table name for the Company entity.
	// It exists in this package in order to avoid circular dependency with the "company" package.
	CompanyInverseTable = "companies"
	// CompanyColumn is the table column denoting the company relation/edge.
	CompanyColumn = "company_order_companyy"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "orders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_order_userr"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldAMOUNT,
	FieldPRICE,
	FieldADDEDTIME,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Order type.
var ForeignKeys = []string{
	"company_order_companyy",
	"equipment_order_equipmentt",
	"user_order_userr",
}
