// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B6104641/app/ent/equipment"
	"github.com/B6104641/app/ent/order"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// EquipmentCreate is the builder for creating a Equipment entity.
type EquipmentCreate struct {
	config
	mutation *EquipmentMutation
	hooks    []Hook
}

// SetEQUIPMENTNAME sets the EQUIPMENT_NAME field.
func (ec *EquipmentCreate) SetEQUIPMENTNAME(s string) *EquipmentCreate {
	ec.mutation.SetEQUIPMENTNAME(s)
	return ec
}

// SetEQUIPMENTPRICE sets the EQUIPMENT_PRICE field.
func (ec *EquipmentCreate) SetEQUIPMENTPRICE(i int) *EquipmentCreate {
	ec.mutation.SetEQUIPMENTPRICE(i)
	return ec
}

// AddOrderEquipmenttIDs adds the order_equipmentt edge to Order by ids.
func (ec *EquipmentCreate) AddOrderEquipmenttIDs(ids ...int) *EquipmentCreate {
	ec.mutation.AddOrderEquipmenttIDs(ids...)
	return ec
}

// AddOrderEquipmentt adds the order_equipmentt edges to Order.
func (ec *EquipmentCreate) AddOrderEquipmentt(o ...*Order) *EquipmentCreate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ec.AddOrderEquipmenttIDs(ids...)
}

// Mutation returns the EquipmentMutation object of the builder.
func (ec *EquipmentCreate) Mutation() *EquipmentMutation {
	return ec.mutation
}

// Save creates the Equipment in the database.
func (ec *EquipmentCreate) Save(ctx context.Context) (*Equipment, error) {
	if _, ok := ec.mutation.EQUIPMENTNAME(); !ok {
		return nil, &ValidationError{Name: "EQUIPMENT_NAME", err: errors.New("ent: missing required field \"EQUIPMENT_NAME\"")}
	}
	if _, ok := ec.mutation.EQUIPMENTPRICE(); !ok {
		return nil, &ValidationError{Name: "EQUIPMENT_PRICE", err: errors.New("ent: missing required field \"EQUIPMENT_PRICE\"")}
	}
	var (
		err  error
		node *Equipment
	)
	if len(ec.hooks) == 0 {
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EquipmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ec.mutation = mutation
			node, err = ec.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			mut = ec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EquipmentCreate) SaveX(ctx context.Context) *Equipment {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ec *EquipmentCreate) sqlSave(ctx context.Context) (*Equipment, error) {
	e, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	e.ID = int(id)
	return e, nil
}

func (ec *EquipmentCreate) createSpec() (*Equipment, *sqlgraph.CreateSpec) {
	var (
		e     = &Equipment{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: equipment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: equipment.FieldID,
			},
		}
	)
	if value, ok := ec.mutation.EQUIPMENTNAME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: equipment.FieldEQUIPMENTNAME,
		})
		e.EQUIPMENTNAME = value
	}
	if value, ok := ec.mutation.EQUIPMENTPRICE(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: equipment.FieldEQUIPMENTPRICE,
		})
		e.EQUIPMENTPRICE = value
	}
	if nodes := ec.mutation.OrderEquipmenttIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipment.OrderEquipmenttTable,
			Columns: []string{equipment.OrderEquipmenttColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return e, _spec
}
