// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/B6104641/app/ent/company"
	"github.com/B6104641/app/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	companyFields := schema.Company{}.Fields()
	_ = companyFields
	// companyDescCOMPANYName is the schema descriptor for COMPANY_Name field.
	companyDescCOMPANYName := companyFields[0].Descriptor()
	// company.COMPANYNameValidator is a validator for the "COMPANY_Name" field. It is called by the builders before save.
	company.COMPANYNameValidator = companyDescCOMPANYName.Validators[0].(func(string) error)
}
