// Code generated by entc, DO NOT EDIT.

package company

const (
	// Label holds the string label denoting the company type in the database.
	Label = "company"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCOMPANYName holds the string denoting the company_name field in the database.
	FieldCOMPANYName = "company_name"

	// EdgeOrderCompanyy holds the string denoting the order_companyy edge name in mutations.
	EdgeOrderCompanyy = "order_companyy"

	// Table holds the table name of the company in the database.
	Table = "companies"
	// OrderCompanyyTable is the table the holds the order_companyy relation/edge.
	OrderCompanyyTable = "orders"
	// OrderCompanyyInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrderCompanyyInverseTable = "orders"
	// OrderCompanyyColumn is the table column denoting the order_companyy relation/edge.
	OrderCompanyyColumn = "company_order_companyy"
)

// Columns holds all SQL columns for company fields.
var Columns = []string{
	FieldID,
	FieldCOMPANYName,
}

var (
	// COMPANYNameValidator is a validator for the "COMPANY_Name" field. It is called by the builders before save.
	COMPANYNameValidator func(string) error
)
