/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Order
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersOrder
 */
export interface ControllersOrder {
    /**
     * 
     * @type {string}
     * @memberof ControllersOrder
     */
    added?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersOrder
     */
    amount?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    company?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    equipment?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    user?: number;
}

export function ControllersOrderFromJSON(json: any): ControllersOrder {
    return ControllersOrderFromJSONTyped(json, false);
}

export function ControllersOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'added': !exists(json, 'added') ? undefined : json['added'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'equipment': !exists(json, 'equipment') ? undefined : json['equipment'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function ControllersOrderToJSON(value?: ControllersOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added': value.added,
        'amount': value.amount,
        'company': value.company,
        'equipment': value.equipment,
        'price': value.price,
        'user': value.user,
    };
}


