/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Order
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEquipmentEdges,
    EntEquipmentEdgesFromJSON,
    EntEquipmentEdgesFromJSONTyped,
    EntEquipmentEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntEquipment
 */
export interface EntEquipment {
    /**
     * EQUIPMENTNAME holds the value of the "EQUIPMENT_NAME" field.
     * @type {string}
     * @memberof EntEquipment
     */
    eQUIPMENTNAME?: string;
    /**
     * EQUIPMENTPRICE holds the value of the "EQUIPMENT_PRICE" field.
     * @type {number}
     * @memberof EntEquipment
     */
    eQUIPMENTPRICE?: number;
    /**
     * 
     * @type {EntEquipmentEdges}
     * @memberof EntEquipment
     */
    edges?: EntEquipmentEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntEquipment
     */
    id?: number;
}

export function EntEquipmentFromJSON(json: any): EntEquipment {
    return EntEquipmentFromJSONTyped(json, false);
}

export function EntEquipmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntEquipment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eQUIPMENTNAME': !exists(json, 'EQUIPMENT_NAME') ? undefined : json['EQUIPMENT_NAME'],
        'eQUIPMENTPRICE': !exists(json, 'EQUIPMENT_PRICE') ? undefined : json['EQUIPMENT_PRICE'],
        'edges': !exists(json, 'edges') ? undefined : EntEquipmentEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntEquipmentToJSON(value?: EntEquipment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'EQUIPMENT_NAME': value.eQUIPMENTNAME,
        'EQUIPMENT_PRICE': value.eQUIPMENTPRICE,
        'edges': EntEquipmentEdgesToJSON(value.edges),
        'id': value.id,
    };
}


